
#List of ranks
[[ranks]]
	tier = 0
	numAffixes = 0
	defaultColor = "#FFFFFF"
	weight = 10000000
	growthFactor = 0
	effects = []
	presetAffixes = ["arctic","desecrating","infested","hasty","lively","paralyzing","molten","wounding"]

[[ranks]]
	tier = 2
	numAffixes = 2
	defaultColor = "#FFFFFF"
	weight = 1
	growthFactor = 2
	effects = []
	presetAffixes = ["arctic","desecrating","infested","hasty","lively","paralyzing","molten","wounding"]

[[ranks]]
	tier = 3
	numAffixes = 3
	defaultColor = "#00FF00"
	weight = 1
	growthFactor = 0
	effects = []
	presetAffixes = ["arctic","desecrating","infested","hasty","lively","paralyzing","molten","wounding"]

[[ranks]]
	tier = 4
	numAffixes = 4
	defaultColor = "#00FFFF"
	weight = 1
	growthFactor = 3
	effects = []
	presetAffixes = ["arctic","desecrating","infested","hasty","lively","paralyzing","molten","wounding"]

[[ranks]]
	tier = 5
	numAffixes = 5
	defaultColor = "#0000FF"
	weight = 1
	growthFactor = 10
	effects = []
	presetAffixes = ["arctic","desecrating","infested","hasty","lively","paralyzing","molten","wounding"]

[[ranks]]
	tier = 6
	numAffixes = 6
	defaultColor = "#FF00FF"
	weight = 1
	growthFactor = 10
	effects = []
	presetAffixes = ["arctic","desecrating","infested","hasty","lively","paralyzing","molten","wounding"]

[[ranks]]
	tier = 7
	numAffixes = 7
	defaultColor = "#FF9B00"
	weight = 1
	growthFactor = 15
	effects = []
	presetAffixes = ["arctic","desecrating","infested","hasty","lively","paralyzing","molten","wounding"]

[[ranks]]
	tier = 10
	numAffixes = 10
	defaultColor = "#FF0000"
	weight = 1
	growthFactor = 30
	effects = []
	presetAffixes = ["arctic","desecrating","infested","hasty","lively","paralyzing","molten","wounding"]

